### PR TITLE
New React-based UI

### PR DESCRIPTION
**Pull request by alexkli**
Test URLs:

* https://react--helix-assets-ui--adobe.hlx.page
* https://react--helix-assets-ui--adobe.hlx.page/?q=#sidebar
* https://react--helix-assets-ui--adobe.hlx.page/?assetId=1e4df33b1cb33045d3ebb32c7d848e037c055f6f6

### CODE REVIEW

**Comment by alexkli** [comment]
@theadriann a few things I noticed, somewhat in order of prio (important to less important):

1. default search is empty - should run an empty search against algolia
2. tenant title and logo does not change with`?tenant=<customer>` (which simulates the `<customer>.hlx.media` case), but I guess it would pick it up once on the right branch and with the relevant "config" in scripts.js? (have not inspected the code deeper)
3. lighthouse score is failing (see `helix-bot` comment above)
4. image urls use hostname `https://main--helix-assets-ui--adobe.hlx3.page` but should match the hostname of the site (this will work on any of the helix domains) so they can load faster, due to more connections allowed for same domain requests. [existing code](https://github.com/adobe/helix-assets-ui/blob/4bff20de63c5e41b4460bc78ec3f0a032142d60b/scripts/scripts.js#L406) (see also below)
5. images load slowly in the search results because it is loading full size original images, not optimized (e.g. webp) thumbnails
   * here is normal example: `https://main--helix-assets-ui--adobe.hlx3.page/media_1ffee6cb25714ba605da100cf15350c2e10b101d5.jpeg?width=750&format=webply&optimize=medium`   
   * see existing code [here](https://github.com/adobe/helix-assets-ui/blob/main/blocks/asset-results/asset-results.js#L209-L215) (which does optimize further depending on width/size of the masonry view)
   * also should be using `<picture>` (see code)
6. images: maybe also do the same eager loading approach from [here](https://github.com/adobe/helix-assets-ui/blob/main/blocks/asset-results/asset-results.js#L103-L106) (I noticed images below the fold start loading first sometimes)
7. masonry view: it seems it's currently not the same masonry view we had before, just a smaller grid with less letterboxes
8. download button/action: it asks for confirmation because the URL is not on the same domain. just like for image urls, the download url should use the same domain to fix that. [existing code](https://github.com/adobe/helix-assets-ui/blob/main/blocks/asset-results/asset-results.js#L156-L159)
9. sort by is not working - we removed it before, we would have to tweak the backend again to optimize that, not sure if we have time for that
10. sources & domain facet is missing (and some others, but depends on what the final requirements are)
     * `sourceType` and `sourceDomain`
     * FYI, I just made a change to make the allow list of domains configurable per tenant in `window.tenantDomains`, see [here](https://github.com/adobe/helix-assets-ui/commit/daa4758517bebacaf7d248df0a6a40ccdcbe7cc7)

**Comment by theadriann** [comment]
> @theadriann a few things I noticed, somewhat in order of prio (important to less important):
> 
> 1. default search is empty - should run an empty search against algolia
> 2. tenant title and logo does not change with`?tenant=<customer>` (which simulates the `<customer>.hlx.media` case), but I guess it would pick it up once on the right branch and with the relevant "config" in scripts.js? (have not inspected the code deeper)
> 3. lighthouse score is failing (see `helix-bot` comment above)
> 4. image urls use hostname `https://main--helix-assets-ui--adobe.hlx3.page` but should match the hostname of the site (this will work on any of the helix domains) so they can load faster, due to more connections allowed for same domain requests. [existing code](https://github.com/adobe/helix-assets-ui/blob/4bff20de63c5e41b4460bc78ec3f0a032142d60b/scripts/scripts.js#L406) (see also below)
> 5. images load slowly in the search results because it is loading full size original images, not optimized (e.g. webp) thumbnails
>    
>    * here is normal example: `https://main--helix-assets-ui--adobe.hlx3.page/media_1ffee6cb25714ba605da100cf15350c2e10b101d5.jpeg?width=750&format=webply&optimize=medium`
>    * see existing code [here](https://github.com/adobe/helix-assets-ui/blob/main/blocks/asset-results/asset-results.js#L209-L215) (which does optimize further depending on width/size of the masonry view)
>    * also should be using `<picture>` (see code)
> 6. images: maybe also do the same eager loading approach from [here](https://github.com/adobe/helix-assets-ui/blob/main/blocks/asset-results/asset-results.js#L103-L106) (I noticed images below the fold start loading first sometimes)
> 7. masonry view: it seems it's currently not the same masonry view we had before, just a smaller grid with less letterboxes
> 8. download button/action: it asks for confirmation because the URL is not on the same domain. just like for image urls, the download url should use the same domain to fix that. [existing code](https://github.com/adobe/helix-assets-ui/blob/main/blocks/asset-results/asset-results.js#L156-L159)
> 9. sort by is not working - we removed it before, we would have to tweak the backend again to optimize that, not sure if we have time for that
> 10. sources & domain facet is missing (and some others, but depends on what the final requirements are)
>     
>     * `sourceType` and `sourceDomain`
>     * FYI, I just made a change to make the allow list of domains configurable per tenant in `window.tenantDomains`, see [here](https://github.com/adobe/helix-assets-ui/commit/daa4758517bebacaf7d248df0a6a40ccdcbe7cc7)


1. in the current design files, there's an empty state that should be displayed when accessing the website instead of showing a bunch of irrelevant assets.
2. the prototype picks up all of the required variables from the scripts file (actually from window) and I have updated it to also pickup the tenant from the query param as well.
3. did a bunch of testing including code-splitting and lazy loading. it did pass most of the tests lately.
4. updated the code to use the same hostname instead
5. updated to use the same technique as you (with the `picture` tag).
6. I don't really know if the implementation of the grid view allows to pre-load the assets that will soon come into view but I left it as an exploration with a low priority.
7. that is the default implementation of the spectrum masonry view. However, I do feel as well that it should be more image-centered so I hacked it to look better.
8. the image urls used for downloading an asset have the same domain as the website you're on.
9. implemented the sort function in the client (will do another round of testing it and improve if necessary and time allows)
10. in the current designs I've only seen the `sourceType` facet which is included in the prototype. I can also add `sourceDomain` once we have an update including it.

**Comment by alexkli** [comment]
FYI, I fixed the Test URLs in the description above from `hlx3.page` to `hlx.page` so that the lighthouse score measurement (helix-psi-check) works again.

**Comment by alexkli** [comment]
Replaced by #46 and #47.

**Pull request closed without merging**
